package com.happymouse.cryd.model.entity;

import jakarta.persistence.*;
import java.time.LocalDateTime;

/**
 * 学习路径实体
 */
@Entity
@Table(name = "learning_path")
public class LearningPath {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(nullable = false, length = 200)
    private String name;

    private Long studentId;

    @Column(columnDefinition = "TEXT")
    private String steps;

    private Integer currentStep;
    private Integer totalSteps;

    @Column(length = 20)
    private String status;

    @Column(columnDefinition = "TEXT")
    private String calendarData;

    @Column(length = 10)
    private String isAutoGenerated; // "0" or "1"

    private Long adjustedBy;

    private LocalDateTime createdAt;

    @PrePersist
    protected void onCreate() {
        createdAt = LocalDateTime.now();
        if (status == null) status = "active";
        if (currentStep == null) currentStep = 0;
    }

    public Long getId() { return id; }
    public void setId(Long id) { this.id = id; }
    public String getName() { return name; }
    public void setName(String name) { this.name = name; }
    public Long getStudentId() { return studentId; }
    public void setStudentId(Long studentId) { this.studentId = studentId; }
    public String getSteps() { return steps; }
    public void setSteps(String steps) { this.steps = steps; }
    public Integer getCurrentStep() { return currentStep; }
    public void setCurrentStep(Integer currentStep) { this.currentStep = currentStep; }
    public Integer getTotalSteps() { return totalSteps; }
    public void setTotalSteps(Integer totalSteps) { this.totalSteps = totalSteps; }
    public String getStatus() { return status; }
    public void setStatus(String status) { this.status = status; }
    public String getCalendarData() { return calendarData; }
    public void setCalendarData(String calendarData) { this.calendarData = calendarData; }
    public String getIsAutoGenerated() { return isAutoGenerated; }
    public void setIsAutoGenerated(String isAutoGenerated) { this.isAutoGenerated = isAutoGenerated; }
    public Long getAdjustedBy() { return adjustedBy; }
    public void setAdjustedBy(Long adjustedBy) { this.adjustedBy = adjustedBy; }
    public LocalDateTime getCreatedAt() { return createdAt; }
    public void setCreatedAt(LocalDateTime createdAt) { this.createdAt = createdAt; }
}
