package com.happymouse.cryd.controller;

import com.happymouse.cryd.common.Result;
import com.happymouse.cryd.model.entity.LearningCheckin;
import com.happymouse.cryd.model.entity.LearningPath;
import com.happymouse.cryd.repository.LearningCheckinRepository;
import com.happymouse.cryd.repository.LearningPathRepository;
import com.happymouse.cryd.repository.StudentRepository;
import com.happymouse.cryd.service.agent.PathPlannerAgent;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.web.bind.annotation.*;

import java.time.LocalDate;
import java.util.List;
import java.util.Map;

/**
 * 学习路径控制器 — 路径生成、手动调整、打卡、学习日历
 */
@RestController
@RequestMapping("/api/learning-path")
public class LearningPathController {

    private static final Logger log = LoggerFactory.getLogger(LearningPathController.class);

    private final LearningPathRepository pathRepo;
    private final LearningCheckinRepository checkinRepo;
    private final StudentRepository studentRepo;
    private final PathPlannerAgent pathPlannerAgent;

    public LearningPathController(LearningPathRepository pathRepo,
                                   LearningCheckinRepository checkinRepo,
                                   StudentRepository studentRepo,
                                   PathPlannerAgent pathPlannerAgent) {
        this.pathRepo = pathRepo;
        this.checkinRepo = checkinRepo;
        this.studentRepo = studentRepo;
        this.pathPlannerAgent = pathPlannerAgent;
    }

    // 获取学生活跃路径
    @GetMapping("/student/{studentId}")
    public Result<List<LearningPath>> getPaths(@PathVariable Long studentId) {
        return Result.success(pathRepo.findByStudentId(studentId));
    }

    // 获取活跃路径
    @GetMapping("/student/{studentId}/active")
    public Result<LearningPath> getActivePath(@PathVariable Long studentId) {
        return Result.success(pathRepo.findByStudentIdAndStatus(studentId, "active").orElse(null));
    }

    // 手动调整路径
    @PutMapping("/{pathId}")
    public Result<LearningPath> updatePath(@PathVariable Long pathId, @RequestBody Map<String, Object> body) {
        LearningPath path = pathRepo.findById(pathId).orElse(null);
        if (path == null) return Result.error("路径不存在");

        if (body.containsKey("steps")) path.setSteps((String) body.get("steps"));
        if (body.containsKey("currentStep")) path.setCurrentStep((Integer) body.get("currentStep"));
        if (body.containsKey("totalSteps")) path.setTotalSteps((Integer) body.get("totalSteps"));
        if (body.containsKey("status")) path.setStatus((String) body.get("status"));
        if (body.containsKey("isAutoGenerated")) path.setIsAutoGenerated((String) body.get("isAutoGenerated"));
        if (body.containsKey("adjustedBy")) path.setAdjustedBy(toLong(body.get("adjustedBy")));

        pathRepo.save(path);
        return Result.success(path);
    }

    // 学习打卡
    @PostMapping("/checkin")
    public Result<LearningCheckin> checkin(@RequestBody Map<String, Object> body) {
        Long studentId = toLong(body.get("studentId"));
        Long stepId = toLong(body.get("pathStepId"));
        String desc = (String) body.get("description");

        LearningCheckin checkin = new LearningCheckin();
        checkin.setStudentId(studentId);
        checkin.setPathStepId(stepId);
        checkin.setDescription(desc);
        checkin.setCheckinDate(LocalDate.now());
        checkinRepo.save(checkin);

        // 更新学生连续打卡天数 (studentId 是 SysUser.id，需通过 username 查找 Student 实体)
        com.happymouse.cryd.model.entity.Student student = resolveStudent(studentId);
        if (student != null) {
            LocalDate today = LocalDate.now();
            LocalDate lastCheckin = student.getLastCheckinDate();
            if (lastCheckin != null && lastCheckin.equals(today.minusDays(1))) {
                student.setStreakDays((student.getStreakDays() != null ? student.getStreakDays() : 0) + 1);
            } else if (lastCheckin == null || !lastCheckin.equals(today)) {
                student.setStreakDays(1);
            }
            student.setLastCheckinDate(today);
            studentRepo.save(student);
        }

        return Result.success(checkin);
    }

    // 获取打卡日历（当月）
    @GetMapping("/checkin/calendar/{studentId}")
    public Result<?> getCalendar(@PathVariable Long studentId,
                                  @RequestParam(required = false) String month) {
        LocalDate today = LocalDate.now();
        LocalDate start = today.withDayOfMonth(1);
        LocalDate end = today.withDayOfMonth(today.lengthOfMonth());
        if (month != null) {
            String[] parts = month.split("-");
            if (parts.length == 2) {
                start = LocalDate.of(today.getYear(), Integer.parseInt(parts[0]), 1);
                end = start.withDayOfMonth(start.lengthOfMonth());
            }
        }

        List<LearningCheckin> checkins = checkinRepo.findByStudentIdAndCheckinDateBetween(studentId, start, end);
        com.happymouse.cryd.model.entity.Student student = resolveStudent(studentId);

        return Result.success(Map.of(
            "checkins", checkins,
            "streakDays", student != null ? student.getStreakDays() : 0,
            "month", start.getMonthValue(),
            "year", start.getYear()
        ));
    }

    // 今日是否已打卡
    @GetMapping("/checkin/today/{studentId}")
    public Result<?> todayCheckin(@PathVariable Long studentId) {
        boolean checked = checkinRepo.existsByStudentIdAndCheckinDate(studentId, LocalDate.now());
        return Result.success(Map.of("checkedIn", checked));
    }

    // AI生成个性化学习路径
    @PostMapping("/generate/{studentId}")
    public Result<LearningPath> generatePath(@PathVariable Long studentId) {
        try {
            var request = new com.happymouse.cryd.model.dto.ChatRequest();
            request.setStudentId(studentId);
            request.setMessage("请根据我的学习情况，生成一个完整的C语言学习路径");

            com.happymouse.cryd.model.dto.ChatResponse response = pathPlannerAgent.generate(request);

            if (response == null || response.getMessage() == null || response.getMessage().trim().isEmpty()) {
                return Result.error(500, "AI路径生成失败：返回内容为空，请稍后重试");
            }

            String content = response.getMessage().trim();
            // 检查是否是错误信息
            if (content.startsWith("抱歉") || content.startsWith("AI服务")) {
                return Result.error(500, "AI路径生成失败：" + content);
            }

            // 生成成功后，删除旧路径
            List<LearningPath> oldPaths = pathRepo.findByStudentId(studentId);
            pathRepo.deleteAll(oldPaths);

            LearningPath path = new LearningPath();
            path.setStudentId(studentId);
            path.setName("AI个性化学习路径");
            path.setSteps(content);
            path.setTotalSteps(10);
            path.setCurrentStep(1);
            path.setStatus("active");
            path.setIsAutoGenerated(true);
            pathRepo.save(path);
            log.info("AI学习路径已生成: studentId={}", studentId);
            return Result.success(path);
        } catch (Exception e) {
            log.error("AI学习路径生成失败: studentId={}, error={}", studentId, e.getMessage(), e);
            return Result.error(500, "AI路径生成失败：" + e.getMessage());
        }
    }

    private Long toLong(Object val) {
        if (val instanceof Number) return ((Number) val).longValue();
        if (val instanceof String) return Long.parseLong((String) val);
        return null;
    }

    /**
     * 通过 SysUser ID 查找对应的 Student 实体
     * Student 实体的 username 格式为 "student_{sysUserId}"
     */
    private com.happymouse.cryd.model.entity.Student resolveStudent(Long sysUserId) {
        return studentRepo.findByUsername("student_" + sysUserId).orElse(null);
    }
}
