package com.happymouse.cryd.controller;

import com.happymouse.cryd.common.Result;
import com.happymouse.cryd.model.entity.LearningCheckin;
import com.happymouse.cryd.model.entity.LearningPath;
import com.happymouse.cryd.repository.LearningCheckinRepository;
import com.happymouse.cryd.repository.LearningPathRepository;
import com.happymouse.cryd.repository.StudentRepository;
import com.happymouse.cryd.model.entity.Student;
import com.happymouse.cryd.service.OnboardingService;
import com.happymouse.cryd.service.agent.PathPlannerAgent;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.web.bind.annotation.*;

import java.time.LocalDate;
import java.time.YearMonth;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * 学习路径控制器 — 路径生成、手动调整、打卡、学习日历
 */
@RestController
@RequestMapping("/api/learning-path")
public class LearningPathController {

    private static final Logger log = LoggerFactory.getLogger(LearningPathController.class);

    private final LearningPathRepository pathRepo;
    private final PathPlannerAgent pathPlannerAgent;
    private final LearningCheckinRepository checkinRepo;
    private final StudentRepository studentRepo;
    private final OnboardingService onboardingService;

    public LearningPathController(LearningPathRepository pathRepo,
                                   PathPlannerAgent pathPlannerAgent,
                                   LearningCheckinRepository checkinRepo,
                                   StudentRepository studentRepo,
                                   OnboardingService onboardingService) {
        this.pathRepo = pathRepo;
        this.pathPlannerAgent = pathPlannerAgent;
        this.checkinRepo = checkinRepo;
        this.studentRepo = studentRepo;
        this.onboardingService = onboardingService;
    }

    /** 监控：未完成AI导学不能生成/查看学习路径 */
    private boolean isOnboardingDone(Long sysUserId) {
        Student s = studentRepo.findByUsername("student_" + sysUserId).orElse(null);
        if (s == null) return false;
        return onboardingService.calcCompleteness(s) >= 80;
    }

    // 获取学生活跃路径
    @GetMapping("/student/{studentId}")
    public Result<List<LearningPath>> getPaths(@PathVariable Long studentId) {
        if (!isOnboardingDone(studentId))
            return Result.error(403, "请先完成AI导学，让我了解你的学习情况再生成学习路径");
        return Result.success(pathRepo.findByStudentId(studentId));
    }

    // 获取活跃路径
    @GetMapping("/student/{studentId}/active")
    public Result<LearningPath> getActivePath(@PathVariable Long studentId) {
        if (!isOnboardingDone(studentId))
            return Result.error(403, "请先完成AI导学");
        return Result.success(pathRepo.findByStudentIdAndStatus(studentId, "active").orElse(null));
    }

    // 手动调整路径
    @PutMapping("/{pathId}")
    public Result<LearningPath> updatePath(@PathVariable Long pathId, @RequestBody Map<String, Object> body) {
        LearningPath path = pathRepo.findById(pathId).orElse(null);
        if (path == null) return Result.error("路径不存在");

        if (body.containsKey("steps")) path.setSteps((String) body.get("steps"));
        if (body.containsKey("currentStep")) path.setCurrentStep((Integer) body.get("currentStep"));
        if (body.containsKey("totalSteps")) path.setTotalSteps((Integer) body.get("totalSteps"));
        if (body.containsKey("status")) path.setStatus((String) body.get("status"));
        if (body.containsKey("isAutoGenerated")) path.setIsAutoGenerated((String) body.get("isAutoGenerated"));
        if (body.containsKey("adjustedBy")) path.setAdjustedBy(toLong(body.get("adjustedBy")));

        pathRepo.save(path);
        return Result.success(path);
    }

    // AI生成个性化学习路径
    @PostMapping("/generate/{studentId}")
    public Result<LearningPath> generatePath(@PathVariable Long studentId) {
        if (!isOnboardingDone(studentId))
            return Result.error(403, "请先完成AI导学，让我了解你的学习情况再生成学习路径");
        try {
            var request = new com.happymouse.cryd.model.dto.ChatRequest();
            request.setStudentId(studentId);
            request.setMessage("请根据我的学习情况，生成一个完整的C语言学习路径");

            com.happymouse.cryd.model.dto.ChatResponse response = pathPlannerAgent.generate(request);

            if (response == null || response.getMessage() == null || response.getMessage().trim().isEmpty()) {
                return Result.error(500, "AI路径生成失败：返回内容为空，请稍后重试");
            }

            String content = response.getMessage().trim();
            // 检查是否是错误信息
            if (content.startsWith("抱歉") || content.startsWith("AI服务")) {
                return Result.error(500, "AI路径生成失败：" + content);
            }

            // 生成成功后，删除旧路径
            List<LearningPath> oldPaths = pathRepo.findByStudentId(studentId);
            pathRepo.deleteAll(oldPaths);

            LearningPath path = new LearningPath();
            path.setStudentId(studentId);
            path.setName("AI个性化学习路径");
            path.setSteps(content);
            path.setTotalSteps(10);
            path.setCurrentStep(1);
            path.setStatus("active");
            path.setIsAutoGenerated("1");
            pathRepo.save(path);
            log.info("AI学习路径已生成: studentId={}", studentId);
            return Result.success(path);
        } catch (Exception e) {
            log.error("AI学习路径生成失败: studentId={}, error={}", studentId, e.getMessage(), e);
            return Result.error(500, "AI路径生成失败：" + e.getMessage());
        }
    }

    private Long toLong(Object val) {
        if (val instanceof Number) return ((Number) val).longValue();
        if (val instanceof String) return Long.parseLong((String) val);
        return null;
    }

    @PostMapping("/checkin")
    public Result<Void> checkin(@RequestBody Map<String, Object> body) {
        Long studentId = toLong(body.get("studentId"));
        if (studentId == null) return Result.error("学生ID不能为空");

        LocalDate today = LocalDate.now();
        if (checkinRepo.existsByStudentIdAndCheckinDate(studentId, today)) {
            return Result.error("今日已打卡");
        }

        LearningCheckin checkin = new LearningCheckin();
        checkin.setStudentId(studentId);
        checkin.setCheckinDate(today);
        checkin.setStatus("completed");
        checkinRepo.save(checkin);
        log.info("学生打卡成功: studentId={}, date={}", studentId, today);
        return Result.success(null);
    }

    @GetMapping("/checkin/today/{studentId}")
    public Result<Map<String, Object>> todayCheckin(@PathVariable Long studentId) {
        LocalDate today = LocalDate.now();
        boolean checkedIn = checkinRepo.existsByStudentIdAndCheckinDate(studentId, today);
        Map<String, Object> result = new HashMap<>();
        result.put("checkedIn", checkedIn);
        return Result.success(result);
    }

    @GetMapping("/checkin/calendar/{studentId}")
    public Result<Map<String, Object>> checkinCalendar(@PathVariable Long studentId, @RequestParam String month) {
        YearMonth yearMonth = YearMonth.parse(month);
        LocalDate start = yearMonth.atDay(1);
        LocalDate end = yearMonth.atEndOfMonth();

        List<LearningCheckin> checkins = checkinRepo.findByStudentIdAndCheckinDateBetween(studentId, start, end);
        List<String> checkinDates = checkins.stream()
            .map(c -> c.getCheckinDate().toString())
            .toList();

        int streakDays = calculateStreakDays(studentId);

        Map<String, Object> result = new HashMap<>();
        result.put("checkinDates", checkinDates);
        result.put("streakDays", streakDays);
        return Result.success(result);
    }

    private int calculateStreakDays(Long studentId) {
        List<LearningCheckin> checkins = checkinRepo.findByStudentIdOrderByCheckinDateDesc(studentId);
        if (checkins.isEmpty()) return 0;

        int streak = 0;
        LocalDate currentDate = LocalDate.now();
        LocalDate yesterday = currentDate.minusDays(1);

        for (LearningCheckin checkin : checkins) {
            if (checkin.getCheckinDate().equals(currentDate)) {
                streak++;
                currentDate = currentDate.minusDays(1);
            } else if (checkin.getCheckinDate().equals(yesterday)) {
                streak++;
                currentDate = yesterday;
                yesterday = currentDate.minusDays(1);
            } else {
                break;
            }
        }
        return streak;
    }
}