package com.happymouse.cryd.config;

import org.hibernate.dialect.PostgreSQLDialect;
import org.hibernate.dialect.identity.IdentityColumnSupport;
import org.hibernate.dialect.identity.IdentityColumnSupportImpl;

/**
 * openGauss 自定义 Hibernate 方言。
 * openGauss 不支持 PostgreSQL 的 GENERATED BY DEFAULT AS IDENTITY 语法，
 * 因此回退到 SERIAL/BIGSERIAL 自增列。
 */
public class OpenGaussDialect extends PostgreSQLDialect {

    @Override
    public IdentityColumnSupport getIdentityColumnSupport() {
        return new IdentityColumnSupportImpl() {
            @Override
            public boolean supportsIdentityColumns() {
                return true;
            }

            @Override
            public String getIdentityColumnString(int type) {
                return "bigserial not null";
            }

            @Override
            public String getIdentitySelectString(String table, String column, int type) {
                return "select currval(pg_get_serial_sequence('" + table + "', '" + column + "'))";
            }

            @Override
            public boolean hasDataTypeInIdentityColumn() {
                return false;
            }

            @Override
            public String getIdentityInsertString() {
                return "default";
            }
        };
    }
}
